apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot
    spec:
      containers:
      - image: teodorrussu/spring-boot-on-kubernetes
        name: spring-boot-on-kubernetes
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot
  name: spring-boot
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot
  type: ClusterIP
status:
  loadBalancer: {}
